### PR TITLE
fix(619): keep-alive e2e aligns with #777 edit-mode visibility (+ pi-ai server-external)

### PR DESCRIPTION
**Pull request by wyuc**
Fixes the `interactive-iframe-keepalive-619.spec.ts` e2e that has been red on `main` since #777. Two related #777-fallout fixes.

## 1. The actual e2e cause: test asserted pre-#777 behavior (primary)

#777 deliberately changed `InteractiveIframeHost.tsx` — it dropped the `mode !== 'edit'` guard so the interactive iframe **stays visible in Pro/edit mode**:

```diff
- visible={mode !== 'edit' && entry.owner !== null && sceneId === activeSceneId}
+ visible={entry.owner !== null && sceneId === activeSceneId}
```

with an explicit rationale in the doc comment it added: *"the editor agent fixes interactive HTML, so the teacher must see the live page while editing."* That is the intended behavior — but the #619 keep-alive e2e was never updated, so its `toBeHidden()` at line 189 ("hidden in edit mode") failed on every run since #777.

Fix: update Trigger A to the new contract — after the Pro-mode toggle the iframe is **visible** and its in-iframe counter state is preserved (the real keep-alive proof: neither unmounted nor reloaded). Trigger B (scene switch to a slide → ownership released → hidden) is unchanged.

## 2. Server-side dynamic-import error spam from #777's agent libs (cleanup)

While investigating, the CI logs showed repeated `Cannot find module as expression is too dynamic` unhandled rejections. These come from `@earendil-works/pi-ai` / `pi-agent-core` (added in #777), which lazily load node builtins via a computed `import(specifier)` that webpack can't statically analyze. They are **not** the e2e cause (the error persisted/cleared independently of the test result), but they are real server-side unhandled rejections. Marking both packages `serverExternalPackages` makes Next load them natively so the dynamic import resolves as a real Node call.

Refs #619, #777.

### CODE REVIEW

**Comment by wyuc** [comment]
**Cross-review (independent Claude + codex passes over the branch diff) — zero actionable findings.**

- `serverExternalPackages`: the `@earendil-works/pi-*` libs do a computed `import(specifier)` for node builtins that webpack can't statically resolve; externalizing lets Node resolve it natively. Both packages are needed (`pi-agent-core` reaches the bad module through `pi-ai`'s `export *`). Scanned the rest of the #777 dep cluster (`@assistant-ui/*`, `streamdown`, `typebox`) — none use the same pattern, nothing missing. No client-bundle impact (the only client-side import is type-only).
- e2e assertion: matches the post-#777 component behavior (the interactive keep-alive iframe now stays visible in edit mode); the keep-alive proof — no remount + preserved counter state — is intact.
